package pigo

// Capability snapshot from pi-commandcode-provider v0.6.4 (adea658),
// generated upstream from command-code@1.44.0, including Muse effort overrides.
type commandCodeModelMetadata struct {
	Input           []InputType
	Reasoning       bool
	Efforts         []ModelThinkingLevel
	MaxOutputTokens int
}

var commandCodeModelCatalog = map[string]commandCodeModelMetadata{
	"MiniMaxAI/MiniMax-M3":                  {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"Qwen/Qwen3.6-Max-Preview":              {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"Qwen/Qwen3.6-Plus":                     {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"Qwen/Qwen3.7-Flash":                    {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"Qwen/Qwen3.7-Max":                      {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"Qwen/Qwen3.7-Plus":                     {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"Qwen/Qwen3.8-27B":                      {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "xhigh"}, MaxOutputTokens: 32768},
	"Qwen/Qwen3.8-Flash":                    {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "xhigh"}, MaxOutputTokens: 65536},
	"Qwen/Qwen3.8-Max":                      {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "xhigh"}, MaxOutputTokens: 65536},
	"Qwen/Qwen3.8-Max-0902":                 {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "xhigh"}, MaxOutputTokens: 65536},
	"claude-fable-5":                        {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh", "max"}, MaxOutputTokens: 65536},
	"claude-fable-5-1":                      {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh", "max"}, MaxOutputTokens: 65536},
	"claude-haiku-4-5-20251001":             {Input: []InputType{"text", "image"}, Reasoning: false, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"claude-opus-4-7":                       {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh", "max"}, MaxOutputTokens: 65536},
	"claude-opus-4-8":                       {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh", "max"}, MaxOutputTokens: 65536},
	"claude-opus-5":                         {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh", "max"}, MaxOutputTokens: 65536},
	"claude-sonnet-4-6":                     {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh", "max"}, MaxOutputTokens: 65536},
	"claude-sonnet-5":                       {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh", "max"}, MaxOutputTokens: 65536},
	"deepseek/deepseek-v4-flash":            {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{"high", "max"}, MaxOutputTokens: 65536},
	"deepseek/deepseek-v4-flash-fast":       {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "high", "max"}, MaxOutputTokens: 65536},
	"deepseek/deepseek-v4-flash-vision-exp": {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"high", "max"}, MaxOutputTokens: 65536},
	"deepseek/deepseek-v4-pro":              {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{"high", "max"}, MaxOutputTokens: 65536},
	"google/gemini-3.1-flash-lite":          {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high"}, MaxOutputTokens: 65536},
	"google/gemini-3.5-flash":               {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high"}, MaxOutputTokens: 65536},
	"google/gemini-3.5-flash-lite":          {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high"}, MaxOutputTokens: 65536},
	"google/gemini-3.6-flash":               {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high"}, MaxOutputTokens: 65536},
	"google/gemini-3.7-flash":               {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high"}, MaxOutputTokens: 65536},
	"google/gemini-3.8-flash":               {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high"}, MaxOutputTokens: 65536},
	"gpt-5.3-codex":                         {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh"}, MaxOutputTokens: 65536},
	"gpt-5.4":                               {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh"}, MaxOutputTokens: 65536},
	"gpt-5.4-mini":                          {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high"}, MaxOutputTokens: 65536},
	"gpt-5.5":                               {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh"}, MaxOutputTokens: 65536},
	"gpt-5.6-luna":                          {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh", "max"}, MaxOutputTokens: 65536},
	"gpt-5.6-sol":                           {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh", "max"}, MaxOutputTokens: 65536},
	"gpt-5.6-terra":                         {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh", "max"}, MaxOutputTokens: 65536},
	"meituan/LongCat-2.0:free":              {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"meta/muse-spark-1.1":                   {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"minimal", "low", "medium", "high", "xhigh"}, MaxOutputTokens: 65536},
	"meta/muse-spark-1.2":                   {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"minimal", "low", "medium", "high", "xhigh"}, MaxOutputTokens: 65536},
	"meta/muse-spark-1.2-contributor":       {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"minimal", "low", "medium", "high", "xhigh"}, MaxOutputTokens: 65536},
	"meta/muse-spark-1.3":                   {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"minimal", "low", "medium", "high", "xhigh"}, MaxOutputTokens: 65536},
	"meta/muse-spark-1.3-contributor":       {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"minimal", "low", "medium", "high", "xhigh"}, MaxOutputTokens: 65536},
	"moonshotai/Kimi-K2.5":                  {Input: []InputType{"text", "image"}, Reasoning: false, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"moonshotai/Kimi-K2.6":                  {Input: []InputType{"text", "image"}, Reasoning: false, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"moonshotai/Kimi-K2.7-Code":             {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"moonshotai/Kimi-K2.7-Code-Highspeed":   {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"moonshotai/Kimi-K3":                    {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "high", "max"}, MaxOutputTokens: 65536},
	"nvidia/nemotron-3-ultra-550b-a55b":     {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"poolside/laguna-s-2.1-free":            {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 32768},
	"sakana/fugu-ultra":                     {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"high", "xhigh"}, MaxOutputTokens: 65536},
	"stepfun/Step-3.5-Flash":                {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"stepfun/Step-3.7-Flash":                {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"tencent/hy3-paid":                      {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"tencent/hy4-preview":                   {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high"}, MaxOutputTokens: 65536},
	"thinkingmachines/inkling":              {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"thinkingmachines/inkling-small":        {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"xai/grok-4.5":                          {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high"}, MaxOutputTokens: 65536},
	"xai/grok-4.6":                          {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "medium", "high", "xhigh"}, MaxOutputTokens: 65536},
	"xiaomi/mimo-v2.5":                      {Input: []InputType{"text", "image"}, Reasoning: false, Efforts: []ModelThinkingLevel{}, MaxOutputTokens: 65536},
	"z-ai/glm-5.3-flash":                    {Input: []InputType{"text", "image"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "high", "max"}, MaxOutputTokens: 131072},
	"zai-org/GLM-5.2":                       {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{"high", "max"}, MaxOutputTokens: 65536},
	"zai-org/GLM-5.3":                       {Input: []InputType{"text"}, Reasoning: true, Efforts: []ModelThinkingLevel{"low", "high", "max"}, MaxOutputTokens: 65536},
}

// Display prices in USD per million tokens, verified upstream 2026-09-01.
// DeepSeek rates are the documented off-peak snapshot, not live billing.
// https://commandcode.ai/docs/resources/pricing-limits
var commandCodeModelCosts = map[string]UsageCost{
	"poolside/laguna-s-2.1-free":            {Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	"tencent/hy3-paid":                      {Input: 0.14, Output: 0.58, CacheRead: 0.035, CacheWrite: 0},
	"tencent/hy4-preview":                   {Input: 0.834, Output: 2.501, CacheRead: 0.042, CacheWrite: 0},
	"moonshotai/Kimi-K3":                    {Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 0},
	"moonshotai/Kimi-K2.7-Code":             {Input: 0.95, Output: 4, CacheRead: 0.19, CacheWrite: 0},
	"moonshotai/Kimi-K2.7-Code-Highspeed":   {Input: 1.9, Output: 8, CacheRead: 0.38, CacheWrite: 0},
	"moonshotai/Kimi-K2.6":                  {Input: 0.95, Output: 4, CacheRead: 0.16, CacheWrite: 0},
	"moonshotai/Kimi-K2.5":                  {Input: 0.6, Output: 3, CacheRead: 0.1, CacheWrite: 0},
	"z-ai/glm-5.3-flash":                    {Input: 0.15, Output: 0.5, CacheRead: 0.03, CacheWrite: 0},
	"zai-org/GLM-5.3":                       {Input: 1.4, Output: 4.4, CacheRead: 0.26, CacheWrite: 0},
	"zai-org/GLM-5.2":                       {Input: 1.4, Output: 4.4, CacheRead: 0.26, CacheWrite: 0},
	"zai-org/GLM-5.2-Fast":                  {Input: 3, Output: 10.25, CacheRead: 0.5, CacheWrite: 0},
	"zai-org/GLM-5.1":                       {Input: 1.4, Output: 4.4, CacheRead: 0.26, CacheWrite: 0},
	"zai-org/GLM-5":                         {Input: 1, Output: 3.2, CacheRead: 0.2, CacheWrite: 0},
	"MiniMaxAI/MiniMax-M3":                  {Input: 0.3, Output: 1.2, CacheRead: 0.06, CacheWrite: 0},
	"MiniMaxAI/MiniMax-M2.7":                {Input: 0.3, Output: 1.2, CacheRead: 0.06, CacheWrite: 0},
	"MiniMaxAI/MiniMax-M2.5":                {Input: 0.3, Output: 1.2, CacheRead: 0.03, CacheWrite: 0},
	"deepseek/deepseek-v4-pro":              {Input: 0.66, Output: 1.98, CacheRead: 0.022, CacheWrite: 0},
	"deepseek/deepseek-v4-flash":            {Input: 0.22, Output: 0.66, CacheRead: 0.007, CacheWrite: 0},
	"deepseek/deepseek-v4-flash-vision-exp": {Input: 0.22, Output: 0.66, CacheRead: 0.007, CacheWrite: 0},
	"deepseek/deepseek-v4-flash-fast":       {Input: 0.28, Output: 0.56, CacheRead: 0.07, CacheWrite: 0},
	"Qwen/Qwen3.8-Max":                      {Input: 2, Output: 6, CacheRead: 0.25, CacheWrite: 2.5},
	"Qwen/Qwen3.8-27B":                      {Input: 0.4, Output: 3, CacheRead: 0.04, CacheWrite: 0},
	"Qwen/Qwen3.8-Flash":                    {Input: 0.16, Output: 0.47, CacheRead: 0.016, CacheWrite: 0},
	"Qwen/Qwen3.7-Max":                      {Input: 2.5, Output: 7.5, CacheRead: 0.5, CacheWrite: 3.13},
	"Qwen/Qwen3.7-Plus":                     {Input: 0.4, Output: 1.6, CacheRead: 0.08, CacheWrite: 0.5},
	"Qwen/Qwen3.7-Flash":                    {Input: 0.03, Output: 0.13, CacheRead: 0.006, CacheWrite: 0.038},
	"Qwen/Qwen3.6-Max-Preview":              {Input: 1.3, Output: 7.8, CacheRead: 0.26, CacheWrite: 1.63},
	"Qwen/Qwen3.6-Plus":                     {Input: 0.5, Output: 3, CacheRead: 0.1, CacheWrite: 0},
	"stepfun/Step-3.7-Flash":                {Input: 0.2, Output: 1.15, CacheRead: 0.04, CacheWrite: 0},
	"stepfun/Step-3.5-Flash":                {Input: 0.1, Output: 0.3, CacheRead: 0.02, CacheWrite: 0},
	"xiaomi/mimo-v2.5-pro":                  {Input: 0.435, Output: 0.87, CacheRead: 0.0036, CacheWrite: 0},
	"xiaomi/mimo-v2.5":                      {Input: 0.14, Output: 0.28, CacheRead: 0.0028, CacheWrite: 0},
	"nvidia/nemotron-3-ultra-550b-a55b":     {Input: 0.6, Output: 2.4, CacheRead: 0.12, CacheWrite: 0},
	"sakana/fugu-ultra":                     {Input: 5, Output: 30, CacheRead: 0.5, CacheWrite: 0},
	"thinkingmachines/inkling":              {Input: 1, Output: 4.05, CacheRead: 0.17, CacheWrite: 0},
	"thinkingmachines/inkling-small":        {Input: 0.5, Output: 1.2, CacheRead: 0.1, CacheWrite: 0},
	"meta/muse-spark-1.1":                   {Input: 1.25, Output: 4.25, CacheRead: 0.15, CacheWrite: 0},
	"meta/muse-spark-1.2":                   {Input: 1.25, Output: 4.25, CacheRead: 0.15, CacheWrite: 0},
	"meta/muse-spark-1.2-contributor":       {Input: 0.1, Output: 0.2, CacheRead: 0.002, CacheWrite: 0},
	"claude-sonnet-5":                       {Input: 2, Output: 10, CacheRead: 0.2, CacheWrite: 2.5},
	"claude-sonnet-4-6":                     {Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 3.75},
	"claude-fable-5-1":                      {Input: 10, Output: 50, CacheRead: 0.25, CacheWrite: 12.5},
	"claude-fable-5":                        {Input: 10, Output: 50, CacheRead: 1, CacheWrite: 12.5},
	"claude-opus-5":                         {Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
	"claude-opus-4-8":                       {Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
	"claude-opus-4-7":                       {Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
	"claude-haiku-4-5-20251001":             {Input: 1, Output: 5, CacheRead: 0.1, CacheWrite: 1.25},
	"gpt-5.6-sol":                           {Input: 5, Output: 30, CacheRead: 0.5, CacheWrite: 6.25},
	"gpt-5.6-terra":                         {Input: 2, Output: 12, CacheRead: 0.2, CacheWrite: 2.5},
	"gpt-5.6-luna":                          {Input: 0.2, Output: 1.2, CacheRead: 0.02, CacheWrite: 0.25},
	"gpt-5.5":                               {Input: 5, Output: 30, CacheRead: 0.5, CacheWrite: 0},
	"gpt-5.4":                               {Input: 2.5, Output: 15, CacheRead: 0.25, CacheWrite: 0},
	"gpt-5.3-codex":                         {Input: 2, Output: 8, CacheRead: 0.5, CacheWrite: 0},
	"gpt-5.4-mini":                          {Input: 0.75, Output: 4.5, CacheRead: 0.075, CacheWrite: 0},
	"google/gemini-3.7-flash":               {Input: 1.5, Output: 7.5, CacheRead: 0.15, CacheWrite: 0.08334},
	"google/gemini-3.6-flash":               {Input: 1.5, Output: 7.5, CacheRead: 0.15, CacheWrite: 0},
	"google/gemini-3.5-flash":               {Input: 1.5, Output: 9, CacheRead: 0.15, CacheWrite: 0},
	"google/gemini-3.5-flash-lite":          {Input: 0.3, Output: 2.5, CacheRead: 0.03, CacheWrite: 0},
	"google/gemini-3.1-flash-lite":          {Input: 0.25, Output: 1.5, CacheRead: 0.03, CacheWrite: 0},
	"xai/grok-4.5":                          {Input: 2, Output: 6, CacheRead: 0.5, CacheWrite: 0},
	"xai/grok-4.6":                          {Input: 2, Output: 6, CacheRead: 0.5, CacheWrite: 0},
}

var commandCodeModelCostTiers = map[string][]ModelCostTier{
	"Qwen/Qwen3.7-Plus":  {{InputTokensAbove: 256000, Rates: UsageCost{Input: 1.2, Output: 4.8, CacheRead: 0.24, CacheWrite: 1.5}}},
	"Qwen/Qwen3.7-Flash": {{InputTokensAbove: 32000, Rates: UsageCost{Input: 0.1, Output: 0.4, CacheRead: 0.02, CacheWrite: 0.125}}, {InputTokensAbove: 256000, Rates: UsageCost{Input: 0.2, Output: 0.8, CacheRead: 0.04, CacheWrite: 0.25}}},
	"xai/grok-4.6":       {{InputTokensAbove: 200000, Rates: UsageCost{Input: 4, Output: 12, CacheRead: 1, CacheWrite: 0}}},
}
